import {
  Home,
  Users,
  UserPlus,
  Wrench,
  Plus,
  Calendar,
  Clock,
  FileText,
  Receipt,
  CreditCard,
  Users2,
  Package,
  Package2,
  Truck,
  Car,
  TrendingUp,
  CalendarDays,
  MessageCircle,
  Star,
  Camera,
  Shield,
  CheckCircle2,
  UserCheck,
  HardHat,
  Database,
  MapPin,
  Target,
  Map,
  Building,
  Calculator,
  MessageSquare,
  Bell,
  Video,
  User
} from "lucide-react";

export interface Section {
  id: string;
  label: string;
  icon: any;
}

export const sections = [
  { id: 'home', label: 'Dashboard', icon: Home },
  { id: 'customers', label: 'Customers', icon: Users },
  { id: 'customer-form', label: 'Add Customer', icon: UserPlus },
  { id: 'jobs', label: 'Jobs', icon: Wrench },
  { id: 'job-form', label: 'Create Job', icon: Plus },
  { id: 'schedule', label: 'Schedule', icon: Calendar },
  { id: 'time-tracking', label: 'Time Tracking', icon: Clock },
  { id: 'estimates', label: 'Estimates', icon: FileText },
  { id: 'invoices', label: 'Invoices', icon: Receipt },
  { id: 'expenses', label: 'Expenses', icon: CreditCard },
  { id: 'team-management', label: 'Team Management', icon: Users2 },
  { id: 'materials-services', label: 'Materials & Services', icon: Package },
  { id: 'inventory', label: 'Inventory', icon: Package2 },
  { id: 'equipment', label: 'Equipment', icon: Truck },
  { id: 'vehicles', label: 'Vehicles', icon: Car },
  { id: 'pipeline', label: 'Sales Pipeline', icon: TrendingUp },
  { id: 'client-appointment', label: 'Appointments', icon: CalendarDays },
  { id: 'communication', label: 'Communication', icon: MessageCircle },
  { id: 'reviews', label: 'Reviews', icon: Star },
  { id: 'photos', label: 'Photo Documentation', icon: Camera },
  { id: 'safety', label: 'Safety Management', icon: Shield },
  { id: 'quality', label: 'Quality Control', icon: CheckCircle2 },
  { id: 'hr-features', label: 'HR Features', icon: UserCheck },
  { id: 'subcontractor-management', label: 'Subcontractors', icon: HardHat },
  { id: 'advanced-inventory', label: 'Advanced Inventory', icon: Database },
  { id: 'employee-locations', label: 'Employee Locations', icon: MapPin },
  { id: 'radius-assignment', label: 'Radius Assignment', icon: Target },
  { id: 'location-management', label: 'Location Management', icon: Map },
  { id: 'branch-management', label: 'Branch Management', icon: Building },
  { id: 'goals', label: 'Goals & KPIs', icon: Target },
  { id: 'tax-financial', label: 'Tax & Financial', icon: Calculator },
  { id: 'payment-integration', label: 'Payment Integration', icon: CreditCard },
  { id: 'profit-analysis', label: 'Profit Analysis', icon: TrendingUp },
  { id: 'team-chat', label: 'Team Chat', icon: MessageSquare },
  { id: 'notifications', label: 'Notifications', icon: Bell },
  { id: 'map-view', label: 'Map View', icon: Map },
  { id: 'back-office', label: 'Back Office', icon: Settings },
  { id: 'internal-meetings', label: 'Internal Meetings', icon: Video },
  { id: 'profile', label: 'Profile', icon: User }
];
